WHU1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("request_management.urls")),
]

request_management/urls.py
from django.urls import path
from .views import NewUserRequestListView, NewUserRequestDetailView, NewUserRequestCreateView, NewUserRequestUpdateView, NewUserRequestDeleteView

urlpatterns = [
    path("newuserrequest/new/", NewUserRequestCreateView.as_view(), name="NURnew"),
    path("newuserrequest/<int:pk>/", NewUserRequestDetailView.as_view(), name="NURDetail"),
    path("newuserrequest/<int:pk>/edit/", NewUserRequestUpdateView.as_view(), name="NURedit"),
    path("newuserrequest/<int:pk>/delete/", NewUserRequestDeleteView.as_view(), name="NURdelete"),
    path("", NewUserRequestListView.as_view(), name="NURList"),
]

request_management/models.py
from django.db import models
from django.urls import reverse

class NewUserRequest(models.Model):

    id = models.AutoField(primary_key=True)
    requested_by = models.ForeignKey(
        'auth.User',
        on_delete=models.DO_NOTHING,
    )
    for_firstname = models.CharField(max_length=50)
    for_lastname = models.CharField(max_length=50)

    #start_date = models.DateField(auto_now=False)
    
    class Campuse(models.TextChoices):
        VALENDAR = 'VAL', ('Valendar')
        DUESSELDORF = 'DUS', ('Düsseldorf')
    campus = models.CharField(
        max_length=3,
        choices=Campuse,
        default=Campuse.VALENDAR)
    
    department = models.CharField(max_length=20, default='')
    job_title = models.CharField(max_length=20)
    office = models.CharField(max_length=10)
    supervisor = models.CharField(max_length=20)
    network_access = models.TextField(default='not needed')
    mail_distribution_lists = models.TextField(default='not needed')
    additional_email = models.TextField(default='not needed')
    mystudies = models.BooleanField(default=False)
    ac5 = models.BooleanField(default=False)
    moodle = models.BooleanField(default=False)
    otrs = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    submitted = models.BooleanField(default=False)

    def __str__(self):
        return f"New User Request by {self.requested_by} for {self.for_firstname} {self.for_lastname} on {self.created.date()}"
    
    def get_absolute_url(self):
        return reverse("NURDetail", kwargs={"pk": self.pk})
    
    def get_title(self):
        return f"New User Request by {self.requested_by} for {self.for_firstname} {self.for_lastname} on {self.created.date()}"
    
    def get_info(self):
        return f"{self.job_title} in {self.department}"
    
    

request_management/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import NewUserRequest

class NewUserRequestListView(ListView):
    model = NewUserRequest
    template_name = "NURList.html"

class NewUserRequestDetailView(DetailView):
    model = NewUserRequest
    template_name = "NURDetail.html"

class  NewUserRequestCreateView(CreateView):
    model = NewUserRequest
    template_name = "NURnew.html"
    fields = ['requested_by',
              'for_firstname',
              'for_lastname',
              #'start_date',
              'campus',
              'department',
              'job_title',
              'office',
              'supervisor',
              'network_access',
              'mail_distribution_lists',
              'additional_email',
              'mystudies',
              'ac5',
              'moodle',
              'otrs'
              ]
    
class  NewUserRequestUpdateView(UpdateView):
    model = NewUserRequest
    template_name = "NURedit.html"
    fields = ['requested_by',
              'for_firstname',
              'for_lastname',
              #'start_date',
              'campus',
              'department',
              'job_title',
              'office',
              'supervisor',
              'network_access',
              'mail_distribution_lists',
              'additional_email',
              'mystudies',
              'ac5',
              'moodle',
              'otrs'
              ]
              
class NewUserRequestDeleteView(DeleteView):
    model = NewUserRequest
    template_name = "NURdelete.html"
    success_url = reverse_lazy("NURList")

request_management/templates/NURDetail.html
{% extends "base.html" %}

{% block content%}
<div class="nur-info">
    <h2>{{ newuserrequest.get_title }}</h2>
    <p>{{ newuserrequest.get_info}}</p>
</div>
<a href="{% url 'NURedit' newuserrequest.pk %} ">Edit New User Request</a>
<a href="{% url 'NURdelete' newuserrequest.pk %}">Delete New User Request</a>
{% endblock content %}

request_management/templates/NURList.html
{% extends "base.html" %}

{% block content %}
{% for nur in newuserrequest_list %}
    <div class="nur-info">
        <h2><a href="{{nur.get_absolute_url}}"> {{ nur.get_title }}</a></h2>
        <p>{{ nur.get_info }}</p>
    </div>
{% endfor %}
{% endblock content %}

request_management/templates/NURdelete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete New User Request</h1>
<form action="" method="post"> {% csrf_token %}
    <p>Are you sure to delete "{{newuserrequest.get_title}}"?</p>
<input type="submit" value="Confirm">
</form>
{% endblock content %}

request_management/templates/NURedit.html
{% extends "base.html" %}

{% block content %}
<h1> Edit New User Request </h1>
<form action="" method="post"> {% csrf_token %}
    {{form.as_p}}
<input type="submit" value="update">
</form>
{% endblock content %}

request_management/templates/NURnew.html
{% extends "base.html" %}

{%block content%}
<h1>Create New User Request</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="save">
</form>
{% endblock content %}

request_management/templates/base.html
<html>
    <head>
        <title>WHU Request Management</title>
    </head>
    <body>
        <header>
            <h1><a href="{% url 'NURList' %}">Requestlist</a></h1>
            <a href= "{% url 'NURnew' %}">Create New User Request</a> 
        </header>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>